### ISSUE TITLE
Créer une release

### ISSUE THREAD

**Issue by p-avital** [JulienVdG/iFrenchKeyboard#1]
Bonjour,

Je suis en déplacement, donc je ne peux pas compiler l'APK en ce moment, mais aimerait utiliser mon clavier avec mon portable avec le bon layout, est ce que vous pourriez publier l'APK quelque part ?

Merci :)

**Comment by JulienVdG** [comment]
Désolé je n'ai plus du tout l'environment de developpement pour ça...
